"""Gemini API client wrapper for image generation."""

import mimetypes
from datetime import datetime
from typing import List, Tuple
from google import genai
from google.genai import types

from utils import save_binary_file


class GeminiImageGenerator:
    """Wrapper for Gemini API image generation."""

    def __init__(self, api_key: str):
        """Initialize Gemini client.

        Args:
            api_key: Google Gemini API key

        Raises:
            ValueError: If API key is invalid
        """
        if not api_key or api_key.strip() == "":
            raise ValueError("API key cannot be empty")

        self.client = genai.Client(api_key=api_key)
        self.model = "gemini-3-pro-image-preview"

    def generate_manga(
        self,
        prompt: str,
        aspect_ratio: str,
        image_parts: List[types.Part]
    ) -> Tuple[str, str]:
        """Generate manga image using Gemini API.

        Args:
            prompt: Text prompt for generation
            aspect_ratio: Image aspect ratio (e.g., "3:4", "1:1")
            image_parts: List of image Parts (layout ref and character refs)

        Returns:
            Tuple of (thought_process, image_url)
            - thought_process: AI's thinking process as text
            - image_url: URL path to generated image (relative to static/)

        Raises:
            Exception: If generation fails
        """
        # Build content parts: text prompt + images
        parts = [types.Part.from_text(text=prompt), *image_parts]

        contents = [
            types.Content(
                role="user",
                parts=parts
            )
        ]

        # Configure generation settings
        config = types.GenerateContentConfig(
            image_config=types.ImageConfig(
                aspect_ratio=aspect_ratio,
                image_size="2K"
            ),
            response_modalities=["IMAGE", "TEXT"]
        )

        # Generate with streaming
        thought_process_parts = []
        generated_image_url = None
        file_index = 0
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        for chunk in self.client.models.generate_content_stream(
            model=self.model,
            contents=contents,
            config=config
        ):
            if chunk.parts is None:
                continue

            # Check for image data
            if chunk.parts[0].inline_data and chunk.parts[0].inline_data.data:
                inline_data = chunk.parts[0].inline_data
                data_buffer = inline_data.data
                file_extension = mimetypes.guess_extension(inline_data.mime_type)

                file_name = f"manga_{timestamp}_{file_index}{file_extension}"
                file_path = f"static/outputs/{file_name}"

                save_binary_file(file_path, data_buffer)
                generated_image_url = f"/static/outputs/{file_name}"
                file_index += 1

            # Check for text (thought process)
            else:
                thought_process_parts.append(chunk.text)

        # Join thought process parts
        thought_process = "".join(thought_process_parts)

        if not generated_image_url:
            raise Exception("No image was generated by the API")

        return thought_process, generated_image_url
